config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  unauthenticated do
    root 'pages#home'
  end
  resources :categories
  resources :participants
  resources :dashboard
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_auth_icon.html.erb
<div class="sm:mx-auto sm:w-full sm:max-w-sm">
<%= image_tag("e-harbor-logo.png", width: '30%', height: '30%', alt: "Event Harbor Logo", class:'mx-auto h-10 w-auto') %>
</div>

app/views/shared/_breadcrumbs.html.erb
<nav class="mt-20" aria-label="Breadcrumb">
  <ol class="inline-flex items-center space-x-1 md:space-x-2 rtl:space-x-reverse">
    <li class="inline-flex items-center">
      <a href="#" class="inline-flex items-center text-sm font-medium text-gray-900 hover:text-blue-600 text-gray-900 dark:hover:text-blue-600">
        <svg class="w-3 h-3 me-2.5" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
          <path d="m19.707 9.293-2-2-7-7a1 1 0 0 0-1.414 0l-7 7-2 2a1 1 0 0 0 1.414 1.414L2 10.414V18a2 2 0 0 0 2 2h3a1 1 0 0 0 1-1v-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v4a1 1 0 0 0 1 1h3a2 2 0 0 0 2-2v-7.586l.293.293a1 1 0 0 0 1.414-1.414Z"/>
        </svg>
        Dashboard
      </a>
    </li>
    <li>
      <div class="flex items-center">
        <svg class="rtl:rotate-180 w-3 h-3 text-gray-400 mx-1" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
        </svg>
        <a href="#" class="ms-1 text-sm font-medium text-gray-700 hover:text-blue-600 md:ms-2 dark:text-gray-400 dark:hover:text-white">All Categories</a>
      </div>
    </li>

  </ol>
</nav>

app/views/shared/_dashboard.html.erb
<%= render "shared/navbar" %>
<%= render "shared/sidebar" %>

<div class="container">
  <%= render "shared/dashboard_content" %>
</div>

<%= render "shared/footer" %>

app/views/shared/_features.html.erb
<div id="features" class="container" style="background: linear-gradient(90deg, #FFFFFF 0%, #B6B5B5 100%)">

  <div class="flex flex-wrap mb-12">
    <% features = [
      { image: "landing-imgs/analytics.png", title: "Metric Monitoring", description: "Capture vital metrics while you exercise. Monitor your progress and stay informed about your health in real-time." },
      { image: "landing-imgs/categories.png", title: "Categories", description: "Create and organize events into different categories. Easily manage and track RSVPs for each category." },
      { image: "landing-imgs/create.png", title: "Event Creation", description: "Effortlessly create events, set details, and manage RSVPs. Simplify the event planning process with our intuitive interface." },
      { image: "landing-imgs/notifications.png", title: "Notifications", description: "Stay informed with real-time notifications. Receive updates on event activities and important announcements." },
      { image: "landing-imgs/reservations.png", title: "Reservations", description: "Manage and track event reservations effortlessly. Ensure a seamless experience for both organizers and attendees." },
      { image: "landing-imgs/performance.png", title: "Performance", description: "Gauge how well your business is doing with auto generated comparisons of your events to similar categories" }
    ] %>
</div>

    <div class="container mx-auto mt-20 px-6 py-12 bg-gradient-to-b from-white via-gray-100 to-gray-300">
  <h2 class="text-4xl font-bold text-center text-gray-800 mb-12">Features</h2>

  <div class="grid grid-cols-1 md:grid-cols-2 gap-12">
    <% features.each_with_index do |feature, index| %>
      <div class="flex items-center">
        <div class="md:order-<%= index.even? ? '1' : '2' %> md:w-1/2">
          <%= image_tag(feature[:image], class: 'w-full h-auto', alt: feature[:title]) %>
        </div>
        <div class="md:order-<%= index.even? ? '2' : '1' %> md:w-1/2 p-6 bg-white rounded-lg shadow-md">
          <h4 class="text-3xl text-gray-800 font-bold mb-3"><%= feature[:title] %></h4>
          <p class="text-gray-600 mb-8"><%= feature[:description] %></p>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/shared/_hero.html.erb
<div id="home" class="py-20 mb-20" style="background: linear-gradient(90deg, #4D5A93 0%, #2D3158 100%); color: #fff;">
  <div class="container mx-auto px-6">
    <div class="flex flex-col items-center text-center">
      <div class="mb-6">
        <%= image_tag("e-harbor-logo.png", width: '100%', height: 'auto', alt: "Event Harbor Logo") %>
      </div>
      <h2 class="text-4xl md:text-5xl lg:text-6xl font-bold mb-2">
        Event Harbor
      </h2>
      <h3 class="text-lg md:text-xl lg:text-2xl mb-8 text-gray-300">
        Event Management Solutions in a nutshell
      </h3>
      <%= link_to "Get Started", new_user_session_path, class: "bg-white text-blue-800 font-bold rounded-full py-3 px-6 shadow-lg uppercase tracking-wider hover:bg-blue-600 hover:text-white transition duration-300 ease-in-out" %>
    </div>
  </div>
</div>

app/views/shared/_home_nav.html.erb
<nav>
      <div class="container mx-auto px-6 py-2 flex justify-between items-center shadow-sm shadow-neutral-700/10 dark:shadow-black/30 dark:bg-gray-900">
        <a class="font-bold text-2xl lg:text-4xl" href="#">
        <span>
          <%= image_tag("e-harbor-logo.png", width: '30px', height: '30px', alt: "Event Harbor Logo") %>
        </span>
        </a>
        <div class="block lg:hidden">
          <button class="flex items-center px-3 py-2 border rounded text-gray-500 border-gray-600 hover:text-gray-800 hover:border-teal-500 appearance-none focus:outline-none">
            <svg class="fill-current h-3 w-3" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
              <title>Menu</title>
              <path d="M0 3h20v2H0V3zm0 6h20v2H0V9zm0 6h20v2H0v-2z" />
            </svg>
          </button>
        </div>
        <div class="lg:block">
          <ul class="inline-flex">
                         <li>
<%= link_to "Home", "#home", class: "block py-2 pr-2 text-neutral-500 transition duration-150 ease-in-out hover:text-neutral-600 focus:text-neutral-600 disabled:text-black/30 dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 dark:disabled:text-white/30 lg:px-2 [&.active]:text-black/80 dark:[&.active]:text-white/80" %>
</li>

             <li>
              <a>
             <li>
<%= link_to "Features", "#features", class: "block py-2 pr-2 text-neutral-500 transition duration-150 ease-in-out hover:text-neutral-600 focus:text-neutral-600 disabled:text-black/30 dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 dark:disabled:text-white/30 lg:px-2 [&.active]:text-black/80 dark:[&.active]:text-white/80" %>
</li>
              </a>
            </li>
             <li>
              <a>
              <%= link_to "SignIn", new_user_session_path, class: "block py-2 pr-2 text-neutral-500 transition duration-150 ease-in-out hover:text-neutral-600 focus:text-neutral-600 disabled:text-black/30 dark:text-neutral-200 dark:hover:text-neutral-300 dark:focus:text-neutral-300 dark:disabled:text-white/30 lg:px-2 [&.active]:text-black/80 dark:[&.active]:text-white/80" %>
            </li>
             </a>
          </ul>
        </div>
      </div>
    </nav>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="fixed top-0 z-50 w-full bg-white border-b border-gray-200 dark:bg-gray-800 dark:border-gray-700">
  <div class="px-3 py-3 lg:px-5 lg:pl-3">
    <div class="flex items-center justify-between">

      <div class="flex items-center justify-start rtl:justify-end">
        <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg sm:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600">
            <span class="sr-only">Open sidebar</span>
            <svg class="w-6 h-6" aria-hidden="true" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
               <path clip-rule="evenodd" fill-rule="evenodd" d="M2 4.75A.75.75 0 012.75 4h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 4.75zm0 10.5a.75.75 0 01.75-.75h7.5a.75.75 0 010 1.5h-7.5a.75.75 0 01-.75-.75zM2 10a.75.75 0 01.75-.75h14.5a.75.75 0 010 1.5H2.75A.75.75 0 012 10z"></path>
            </svg>
         </button>

        <a class="flex ms-2 md:me-24">
             <%= image_tag("e-harbor-logo.png", width: '30px', height: '30px', alt: "Event Harbor Logo") %>
          <span class="self-center text-xl font-semibold sm:text-2xl whitespace-nowrap dark:text-white">EHarbor</span>
        </a>
      </div>

       <%= render "shared/notifications_dropdown" %>

      <div class="flex items-center">
          <div class="flex items-center ms-3">
            <div>
              <button type="button" class="flex text-sm bg-black-800 rounded-full focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" aria-expanded="false" data-dropdown-toggle="dropdown-user">
                 <svg width="30px" height="30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <circle cx="12" cy="9" r="3" stroke="#c62e67" stroke-width="1.5"></circle> <path d="M17.9691 20C17.81 17.1085 16.9247 15 11.9999 15C7.07521 15 6.18991 17.1085 6.03076 20" stroke="#c62e67" stroke-width="1.5" stroke-linecap="round"></path> <path d="M7 3.33782C8.47087 2.48697 10.1786 2 12 2C17.5228 2 22 6.47715 22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 10.1786 2.48697 8.47087 3.33782 7" stroke="#c62e67" stroke-width="1.5" stroke-linecap="round"></path> </g></svg>
              </button>
            </div>
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600" id="dropdown-user">
              <div class="px-4 py-3" role="none">
                <p class="text-sm text-gray-900 dark:text-white" role="none">
                  Neil Sims
                </p>
                <p class="text-sm font-medium text-gray-900 truncate dark:text-gray-300" role="none">
                  user@user.com
                </p>
              </div>

              <ul class="py-1 bg:gray" role="none">
               <li>
  <%= link_to authenticated_root_path, class: "block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white", role: "menuitem" do %>
    Dashboard
  <% end %>
</li>

                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Settings</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Earnings</a>
                </li>
                <li>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:text-gray-300 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">Sign out</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
    </div>
  </div>
</nav>

app/views/shared/_notifications.html.erb
<div id="toast-notification" class="w-full max-w-xs p-4 text-gray-900 bg-white rounded-lg shadow dark:bg-gray-800 dark:text-gray-300" role="alert">
    <div class="flex items-center mb-3">
        <span class="mb-1 text-sm font-semibold text-gray-900 dark:text-gray-300">New notification</span>
        <button type="button" class="ms-auto -mx-1.5 -my-1.5 bg-white justify-center items-center flex-shrink-0 text-gray-400 hover:text-gray-900 rounded-lg focus:ring-2 focus:outline-none focus:ring-gray-300 p-1.5 hover:bg-gray-100 inline-flex h-8 w-8 dark:text-gray-500 dark:hover:text-white dark:bg-gray-800 dark:hover:bg-gray-700" data-dismiss-target="#toast-notification" aria-label="Close">
            <span class="sr-only">Close</span>
            <%= raw('<svg class="w-4 h-4" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path></svg>') %>
        </button>
    </div>
    <div class="flex items-center" id="notice">
        <div class="relative inline-block shrink-0">
            <%= raw('<span class="h-12 w-12 absolute bottom-0 right-0 inline-flex items-center justify-center w-6 h-6 bg-blue-600 rounded-full"><svg class="w-3 h-3 text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 18" fill="currentColor"><path d="M18 4H16V9C16 10.0609 15.5786 11.0783 14.8284 11.8284C14.0783 12.5786 13.0609 13 12 13H9L6.846 14.615C7.17993 14.8628 7.58418 14.9977 8 15H11.667L15.4 17.8C15.5731 17.9298 15.7836 18 16 18C16.2652 18 16.5196 17.8946 16.7071 17.7071C16.8946 17.5196 17 17.2652 17 17V15H18C18.5304 15 19.0391 14.7893 19.4142 14.4142C19.7893 14.0391 20 13.5304 20 13V6C20 5.46957 19.7893 4.96086 19.4142 4.58579C19.0391 4.21071 18.5304 4 18 4Z" fill="currentColor"/><path d="M12 0H2C1.46957 0 0.960859 0.210714 0.585786 0.585786C0.210714 0.960859 0 1.46957 0 2V9C0 9.53043 0.210714 10.0391 0.585786 10.4142C0.960859 10.7893 1.46957 11 2 11H3V13C3 13.1857 3.05171 13.3678 3.14935 13.5257C3.24698 13.6837 3.38668 13.8114 3.55279 13.8944C3.71889 13.9775 3.90484 14.0126 4.08981 13.996C4.27477 13.9793 4.45143 13.9114 4.6 13.8L8.333 11H12C12.5304 11 13.0391 10.7893 13.4142 10.4142C13.7893 10.0391 14 9.53043 14 9V2C14 1.46957 13.7893 0.960859 13.4142 0.585786C13.0391 0.210714 12.5304 0 12 0Z" fill="currentColor"/></svg></span>') %>
        </div>
        <div class="ms-3 text-sm font-normal">
            <div class="text-slate-500"><%= notice %></div>
        </div>
    </div>
</div>

app/views/shared/_notifications_dropdown.html.erb
<div class="flex items-center">
  <div class="flex items-center mx-3 relative">
            <div>
              <button type="button" class="flex text-sm bg-black-800 rounded-full focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" aria-expanded="false" data-dropdown-toggle="dropdown-notification">
                <svg width="30px" height =" 30px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M8.35179 20.2418C9.19288 21.311 10.5142 22 12 22C13.4858 22 14.8071 21.311 15.6482 20.2418C13.2264 20.57 10.7736 20.57 8.35179 20.2418Z" fill="#FDFDFD"></path> <path d="M18.7491 9V9.7041C18.7491 10.5491 18.9903 11.3752 19.4422 12.0782L20.5496 13.8012C21.5612 15.3749 20.789 17.5139 19.0296 18.0116C14.4273 19.3134 9.57274 19.3134 4.97036 18.0116C3.21105 17.5139 2.43882 15.3749 3.45036 13.8012L4.5578 12.0782C5.00972 11.3752 5.25087 10.5491 5.25087 9.7041V9C5.25087 5.13401 8.27256 2 12 2C15.7274 2 18.7491 5.13401 18.7491 9Z" fill="#FFFFFF"></path> </g>
       <circle cx="15" cy="2" r="2" fill="red" />
       </svg>
              </button>
            </div>
            <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded shadow dark:bg-gray-700 dark:divide-gray-600 w-60" id="dropdown-notification">
              <div class="px-4 py-3" role="none">
                <p class="text-sm font-medium text-dark-900 truncate dark:text-gray-900" role="none">
                 Notifications
                </p>
              </div>
                <ul class="py-1 bg:gray" role="none">
                 <li class="flex items-center">
                  <a href="#" class="flex items-center px-4 py-2 text-sm text-gray-700 hover:bg-gray-600 dark:text-gray-900 dark:hover:bg-gray-600 dark:hover:text-white" role="menuitem">
                   <span class="ms-3">
  <% if notice.present? %>
    <p><%= notice %></p>
  <% else %>
    <p>No Notifications here</p>
  <% end %>
</span>

    </a>
                </li>

                <li class="flex items-center">
                 <svg width="20px" height="20px" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M31.521 55.515V39.515" stroke="#c62e67" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M31.521 28.845V7.51501" stroke="#c62e67" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M31.521 39.514C34.468 39.514 36.857 37.125 36.857 34.178C36.857 31.231 34.468 28.842 31.521 28.842C28.574 28.842 26.185 31.231 26.185 34.178C26.185 37.125 28.574 39.514 31.521 39.514Z" stroke="#426AB2" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M50.191 55.515V31.515" stroke="#c62e67" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M50.191 20.845V7.51501" stroke="#c62e67" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M50.19 31.514C53.137 31.514 55.526 29.125 55.526 26.178C55.526 23.231 53.137 20.842 50.19 20.842C47.243 20.842 44.854 23.231 44.854 26.178C44.854 29.125 47.243 31.514 50.19 31.514Z" stroke="#426AB2" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M12.861 55.515V31.515" stroke="#c62e67" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M12.861 20.845V7.51501" stroke="#c62e67" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M12.857 31.514C15.804 31.514 18.193 29.125 18.193 26.178C18.193 23.231 15.804 20.842 12.857 20.842C9.91 20.842 7.521 23.231 7.521 26.178C7.521 29.125 9.91 31.514 12.857 31.514Z" stroke="#426AB2" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
                  <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-600 dark:text-gray-900 dark:hover:bg-dark-900 dark:hover:text-white" role="menuitem">Clear All</a>
                </li>
              </ul>
            </div>
          </div>
        </div>

app/views/shared/_prefilled_form.html.erb
<%= form_with(model: event, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :name, value: category.name %>
  <%= form.hidden_field :description, value: category.description %>
  <%= form.hidden_field :icon, value: category.icon %>

  <div class="my-5">
    <strong>Category Name:</strong> <%= category.name %>
  </div>

  <div class="my-5">
    <strong>Category Description:</strong> <%= category.description %>
  </div>

  <div class="my-5">
    <strong>Category Icon:</strong> <%= category.icon %>
  </div>

  <div class="my-5">
    <%= form.label :event_name, "Event Name" %>
    <%= form.text_field :event_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>


  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>