config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  unauthenticated do
    root 'pages#home'
  end
  resources :categories
  resources :participants
  resources :dashboard
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :category
  has_many :participants
  attribute :event_type, default: 'Private'
  attribute :reservations, default: false
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :description, length: { maximum: 150 }
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[show edit update destroy]

  # GET /events or /events.json
  def index
    @events = Event.all
    @user_email = current_user.email if user_signed_in?
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)
    @event.event_type = params[:event][:event_type] == '1' ? 'Public' : 'Private'

    respond_to do |format|
      if @event.save
        # Display user email in the notice message
        format.html do
          redirect_to event_url(@event),
                      notice: "Event #{@event.name} was recently created
                      by #{current_user.email} at #{Time.now.strftime('%B %e, %Y %H:%M:%S')}"
        end
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        @event.event_type = params[:event][:event_type] == '1' ? 'Public' : 'Private'
        @event.save

        format.html do
          redirect_to event_url(@event),
                      notice: "An Event was recently updated to #{@event.name}
                    by #{current_user.email} at #{Time.now.strftime('%B %e, %Y %H:%M:%S')}"
        end
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html do
        redirect_to events_url,
                    notice: "Event  #{@event.name} was recently deleted by #{current_user.email}
        at #{Time.now.strftime('%B %e, %Y %H:%M:%S')}"
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :summary, :description, :reservation, :event_type, :price,
                                  :capacity, :tickets_left, :date, :location, :start_time, :end_time, :avatar,
                                  :banner, :category_id, :tickets)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <%= image_tag(event.banner, alt: 'Event Banner', class: 'rounded-t-lg w-full') if event.banner.present? %>
  <div class="p-5">
  <div>
 <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900"><%= event.name %></h5>


 <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900"><%= event.summary %></h5>

  </div>
    <div class="my-5">
      <%= event.description %>
    </div>
    <div class="relative">
      <%= image_tag(event.avatar, alt: 'Event Avatar', class: 'w-10 h-10 rounded-full') if event.avatar.present? %>
      <span class="bottom-0 left-7 absolute w-3.5 h-3.5 bg-green-400 border-2 border-white dark:border-gray-800 rounded-full"></span>
    </div>
    <div class="my-5">
      <strong class="block font-medium mb-1">Reservations:</strong>
      <%= event.reservation %>
    </div>
    <div class="flex">
  <p class="bottom-0 left-7 mb-4 ml-6 mr-10">People attending this event</p>
  <div class="items-center">
    <%= image_tag(event.avatar, alt: 'Event Avatar', class: 'w-10 h-10 border-2 border-white rounded-full dark:border-gray-800') if event.avatar.present? %>
  </div>
  <a class="flex items-center justify-center w-10 h-10 text-xs font-medium text-white bg-gray-400 border-2 border-white rounded-full hover:bg-gray-600 dark:border-gray-800" href="#">+99</a>
</div>

<div class="my-5">
  <strong class="block font-medium mb-1">Event Visibility:</strong>
  <%= event.event_type %>
</div>
<% if action_name != "show" %>
      <%= link_to "Show this event", event, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <%= link_to "Edit this event", edit_event_path(event), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
      <hr class="mt-6">
    <% end %>
  </div>
</div>

app/views/events/_event_card.html.erb
<%= link_to event_path(event) do %>
  <div class="bg-white p-4 rounded-lg shadow-md">
    <%= image_tag(event.avatar, alt: 'Event Avatar', class: 'w-10 h-10 rounded-full') if event.avatar.present? %>
    <%= image_tag(event.banner, alt: 'Event Banner', class: 'rounded-t-lg') if event.banner.present? %>
    <h2 class="text-lg font-semibold mb-2"><%= event.name %></h2>
    <p class="text-gray-600"><%= event.summary %></p>
  </div>
<% end %>

app/views/events/_event_details.html.erb
<% content_for :content do %>
<div class="mx-full md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <%= render "shared/notifications"%>
    <% end %>
    <%= render @event %>
    <%= link_to "Edit this event", edit_event_path(@event), class: "button border-none mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Delete event", event_path(@event), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to events", events_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>
<% end %>
<%= render "shared/dashboard" %>

app/views/events/edit.html.erb
<% content_for :content do %>
<div class="p-4 sm:ml-64 mt-8 mb-8">
  <h1 class="font-bold text-4xl mt-8">Edit event</h1>
  <%= render "form", event: @event %>

  <%= link_to "Show this event", @event, class: "ml-2 rounded-lg py-3 px-5 bg-blue-100 inline-block font-medium" %>
 
</div>
<% end %>
<%= render "shared/dashboard" %>

app/views/events/index.html.erb
<% content_for :content do %>
<div class="p-4 sm:ml-64 mt-8">
  <div class="mx-auto md:w-1/6 w-full">
    <% if notice.present? %>
      <%= render "shared/notifications" %>
    <% end %>
</div>
        <%= render "shared/trending_events" %>
    <div id="events" class="grid grid-cols-2 md:grid-cols-3 gap-6 drop-shadow-md">
      <% @events.each do |event| %>
        <%= link_to event_path(event) do %>
          <div class="bg-white p-4 rounded-lg shadow-md">
            <div class="relative">
              <%= image_tag(event.avatar, alt: 'Event Avatar', class: 'w-10 h-10 rounded-full') if event.avatar.present? %>
              <span class="bottom-0 left-7 absolute w-3.5 h-3.5 bg-green-400 border-2 border-white dark:border-gray-800 rounded-full"></span>
            </div>
            <%= image_tag(event.banner, alt: 'Event Banner', class: 'rounded-t-lg') if event.banner.present? %>
            <h2 class="text-lg font-semibold mb-2"><%= event.name %></h2>
            <p class="text-gray-600"><%= event.description %></p>
            <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Happening Now</span>
          </div>
        <% end %>
      <% end %>
    </div>
     <div class="fixed bottom-0 flex justify-between items-center">
      <%= link_to new_event_path, class: "p-0 w-12 h-12 bg-red-500 rounded-full hover:bg-red-700 active:shadow-lg mouse shadow transition ease-in duration-200 focus:outline-none flex items-center justify-center fixed bottom-4 right-2 z-50" do %>
       <svg width="130px" height="130px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M10 21H6.2C5.0799 21 4.51984 21 4.09202 20.782C3.71569 20.5903 3.40973 20.2843 3.21799 19.908C3 19.4802 3 18.9201 3 17.8V8.2C3 7.0799 3 6.51984 3.21799 6.09202C3.40973 5.71569 3.71569 5.40973 4.09202 5.21799C4.51984 5 5.0799 5 6.2 5H17.8C18.9201 5 19.4802 5 19.908 5.21799C20.2843 5.40973 20.5903 5.71569 20.782 6.09202C21 6.51984 21 7.0799 21 8.2V10M7 3V5M17 3V5M3 9H21M13.5 13.0001L7 13M10 17.0001L7 17M14 21L16.025 20.595C16.2015 20.5597 16.2898 20.542 16.3721 20.5097C16.4452 20.4811 16.5147 20.4439 16.579 20.399C16.6516 20.3484 16.7152 20.2848 16.8426 20.1574L21 16C21.5523 15.4477 21.5523 14.5523 21 14C20.4477 13.4477 19.5523 13.4477 19 14L14.8426 18.1574C14.7152 18.2848 14.6516 18.3484 14.601 18.421C14.5561 18.4853 14.5189 18.5548 14.4903 18.6279C14.458 18.7102 14.4403 18.7985 14.405 18.975L14 21Z" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path> </g></svg>
      <% end %>
    </div>
  </div>
<% end %>
<%= render "shared/dashboard" %>

app/views/events/new.html.erb
 <% content_for :content do %>
<div class="p-4 sm:ml-64">
<div class="mt-4">
<%= link_to events_path, class: "rounded-lg py-3 px-5 inline-block font-medium flex items-center" do %>
        <%= raw('<svg class="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>All Events') %>
      <% end %>
   </div>
    <div class="mr-10"><p class="mt-2 text-4xl text-gray-900 dark:text-gray-900">New Event</p></div>
  <%= render "form", event: @event %>
</div>
</div>
<% end %>
<%= render "shared/dashboard" %>

app/views/events/show.html.erb
<% content_for :content do %>
<div class="p-4 sm:ml-64 mt-8">
  <div class="mx-auto md:w-1/6 w-full">
    <% if notice.present? %>
      <%= render "shared/notifications" %>
    <% end %>
</div>

<div class="mx-full md:w-2/3 w-full flex mt-8">
  <div class="mx-auto">
    <%= render @event %>
    <div class="w-full mt-auto px-4 inline-flex rounded-md shadow-sm" role="group">


  <%= link_to edit_event_path(@event), class: "px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" do %>
    Edit Event
  <% end %>
   <%= link_to events_path, class: "px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" do %>
    Cancel
  <% end %>
   <%= button_to event_path(@event),method: :delete, class: "px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" do %>
    Delete
  <% end %>
   <%= link_to events_path, class: "px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" do %>
    All Events
  <% end %>
</div>

  </div>
   <div class="mt-4">
   <span class="inline-flex items-center rounded-md bg-green-50 px-2 py-1 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">Happening Now</span></div>
</div>




</div>

<% end %>
<%= render "shared/dashboard" %>