config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  unauthenticated do
    root 'pages#home'
  end
  resources :categories
  resources :participants
  resources :dashboard
  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :events, dependent: :destroy
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
    @user_email = current_user.email if user_signed_in?
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @event_count = @category.events.count
  end

  # GET /categories/new
  def new
    @category = Category.new
    icons_json = File.read(Rails.root.join('app/assets/icons.json'))
    icon_data = JSON.parse(icons_json)
    @icon_choices = icon_data.map { |icon| ["#{icon['name']} - #{icon['emoji']}", icon['emoji']] }
  end

  # GET /categories/1/edit
  def edit
    @icon_choices = icon_choices_for_form
  end

  def icon_choices_for_form
    icons_json = File.read(Rails.root.join('app/assets/icons.json'))
    icon_data = JSON.parse(icons_json)
    icon_data.map { |icon| ["#{icon['name']} - #{icon['emoji']}", icon['emoji']] }
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to category_url(@category),
                      notice: "Category #{@category.name} was recently created by
                      #{current_user.email} at #{Time.now.strftime('%B %e, %Y %H:%M:%S')}"
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html do
          redirect_to category_url(@category),
                      notice: "Category was recently updated to #{@category.name}
                      by #{current_user.email} at #{Time.now.strftime('%B %e, %Y %H:%M:%S')}"
        end
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html do
        redirect_to categories_url,
                    notice: "Category  #{@category.name} was recently deleted
                    by #{current_user.email} at #{Time.now.strftime('%B %e, %Y %H:%M:%S')}"
      end
      format.json { head :no_content }
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description, :icon)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<%= link_to category_path(category), class: "block rounded-lg overflow-hidden shadow-md bg-white p-6 my-4" do %>
  <div class="mb-4">
    <p class="text-lg font-semibold text-gray-800"><%= category.name %></p>
  </div>
  <div class="mb-4 flex items-center justify-center">
    <span class="text-7xl text-primary"><%= category.icon %></span>
  </div>
  <% if action_name == "show" %>
    <div class="mb-4 text-center">
      <p class="text-base text-gray-600"><%= category.description %></p>
    </div>
  <% end %>
<% end %>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="flex flex-wrap -mx-4 mb-20">
  <div class="flex flex-wrap -mx-4 mb-20">
  <div class="w-full px-4 md:w-1/2 lg:w-1/3">
    <div class="mb-12">
       <label for="" class="mb-[10px] block text-base font-medium text-dark dark:text-white">
         Name
         </label>
     <%= form.text_field :name, placeholder: "Enter category name", class: "w-full bg-transparent rounded-md border border-stroke dark:border-dark-3 py-[10px] px-5 text-dark-6 outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-gray-2 disabled:border-gray-2" %>
    </div>
    </div>
<div class="w-full px-4 md:w-1/2 lg:w-1/3">
     <div class="">
       <label for="" class="mb-[10px] block text-base font-medium text-dark dark:text-white">
         Description
         </label>
     <%= form.text_field :description, placeholder: "Category Description", class: "w-full bg-transparent rounded-md border border-stroke dark:border-dark-3 py-[10px] px-5 text-dark-6 outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-gray-2 disabled:border-gray-2" %>
    </div>
     </div>
  <div class="flex flex-wrap -mx-4">
  <div class="w-full px-4 md:w-1/2 lg:w-1/3">
    <div class="mb-12">
       <label for="" class="mb-[10px] block text-base font-medium text-dark dark:text-white">
         Name
         </label>
     <%= form.text_field :name, placeholder: "Enter category name", class: "w-full bg-transparent rounded-md border border-stroke dark:border-dark-3 py-[10px] px-5 text-dark-6 outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-gray-2 disabled:border-gray-2" %>
    </div>
    </div>
<div class="w-full px-4 md:w-1/2 lg:w-1/3">
     <div class="">
       <label for="" class="mb-[10px] block text-base font-medium text-dark dark:text-white">
         Description
         </label>
     <%= form.text_field :description, placeholder: "Category Description", class: "w-full bg-transparent rounded-md border border-stroke dark:border-dark-3 py-[10px] px-5 text-dark-6 outline-none transition focus:border-primary active:border-primary disabled:cursor-default disabled:bg-gray-2 disabled:border-gray-2" %>
    </div>
     </div>

    <div class="w-full px-4 md:w-1/2 lg:w-1/3 mb-12">
      <label for="" class="mb-[10px] block text-base font-medium text-dark dark:text-gray-900">
         Select category Icon
         </label>
      <%= form.select :icon, @icon_choices, {}, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    </div>

<div class="w-full mt-auto px-4 inline-flex rounded-md shadow-sm" role="group">
   <%= form.submit class: "cursor-pointer px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" %>

  <%= link_to categories_path, class: "px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" do %>
    All Categories
  <% end %>
   <%= link_to categories_path, class: "px-4 py-2 text-sm font-medium text-gray-900 bg-white border border-gray-200 rounded-s-lg hover:bg-gray-100 hover:text-blue-700 focus:z-10 focus:ring-2 focus:ring-blue-700 focus:text-blue-700 dark:bg-gray-700 dark:border-gray-600 dark:text-white dark:hover:text-white dark:hover:bg-gray-600 dark:focus:ring-blue-500 dark:focus:text-white" do %>
    Cancel
  <% end %>
</div>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :content do %>
<div class="p-4 sm:ml-64 mt-8">
  <h1 class="font-bold text-4xl mt-8">Editing category</h1>

  <div class="mt-4 flex items-center space-x-2 mt-8">
    <%= link_to categories_path, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium flex items-center" do %>
      <%= raw('<svg class="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>All Categories') %>
    <% end %>

    <%= link_to @category, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium flex items-center" do %>
      <%= raw('<svg class="w-6 h-6 mr-2" fill="#111918" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" xml:space="preserve"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <style type="text/css"> .sharpcorners_een{fill:#111918;} .st0{fill:#111918;} </style> <path class="sharpcorners_een" d="M16,6C7,6,2,14,2,16s5,10,14,10s14-8,14-10S25,6,16,6z M16,24c-4.418,0-8-3.582-8-8s3.582-8,8-8 s8,3.582,8,8S20.418,24,16,24z M16,9c-3.86,0-7,3.14-7,7s3.14,7,7,7s7-3.14,7-7S19.86,9,16,9z M16,19c-1.657,0-3-1.343-3-3 s1.343-3,3-3s3,1.343,3,3S17.657,19,16,19z"></path> </g></svg>Show Category') %>
    <% end %>
  </div>

  <%= render "form", category: @category %>
</div>
<% end %>
<%= render "shared/dashboard" %>

app/views/categories/new.html.erb
 <% content_for :content do %>
<div class="p-4 sm:ml-64">
<div class="mt-4">
      <%= link_to categories_path, class: "rounded-lg py-3 px-5 inline-block font-medium flex items-center" do %>
        <%= raw('<svg class="w-6 h-6 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 19l-7-7m0 0l7-7m-7 7h18"></path></svg>All Categories') %>
      <% end %>
    </div>
    <div class="mr-10"><p class="mt-2 text-4xl text-gray-900 dark:text-gray-900">New category</p></div>
  <%= render "form", category: @category %>
</div>
 <% end %>
     <%= render "shared/dashboard"%>

app/views/categories/show.html.erb
<% content_for :content do %>
   <div class="p-4 mt-10 h-96 mb-20 sm:ml-64 bg-white border border-gray-200 shadow dark:bg-gray-800 dark:border-gray-700">
   <div class="md:w-1/6 w-full absolute mt-8">
    <% if notice.present? %>
      <%= render "shared/notifications" %>
    <% end %>

  </div>
<div class="mt-10 w-full h-auto bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
    <ul class="flex inline-flex flex-wrap text-sm font-medium text-center text-gray-500 border-b border-gray-200 rounded-t-lg bg-gray-50 dark:border-gray-700 dark:text-gray-400 dark:bg-gray-800" id="defaultTab" data-tabs-toggle="#defaultTabContent" role="tablist">
      <li class="me-2 mt-2">
      <%= link_to categories_path, class: "text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-white-900" do %>
     <svg width=30px height="30px" viewBox="0 0 1024 1024" fill="#fff" class="icon" version="1.1" xmlns="http://www.w3.org/2000/svg" stroke="#fff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M669.6 849.6c8.8 8 22.4 7.2 30.4-1.6s7.2-22.4-1.6-30.4l-309.6-280c-8-7.2-8-17.6 0-24.8l309.6-270.4c8.8-8 9.6-21.6 2.4-30.4-8-8.8-21.6-9.6-30.4-2.4L360.8 480.8c-27.2 24-28 64-0.8 88.8l309.6 280z" fill=""></path></g></svg>
      <% end %>
    </li>
        <li class="me-2">
            <button id="about-tab" data-tabs-target="#about" type="button" role="tab" aria-controls="about" aria-selected="true" class="inline-block p-4 text-blue-600 rounded-ss-lg hover:bg-gray-100 dark:bg-gray-800 dark:hover:bg-gray-700 dark:text-blue-500">About</button>
        </li>
        <li class="me-2">
            <button id="events-tab" data-tabs-target="#events" type="button" role="tab" aria-controls="events" aria-selected="false" class="inline-block p-4 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-300">Events</button>
        </li>
        <li class="me-2">
            <button id="popularity-tab" data-tabs-target="#popularity" type="button" role="tab" aria-controls="popularity" aria-selected="false" class="inline-block p-4 hover:text-gray-600 hover:bg-gray-100 dark:hover:bg-gray-700 dark:hover:text-gray-300">Popularity</button>
        </li>
    </ul>
<div id="defaultTabContent">
    <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-800" id="about" role="tabpanel" aria-labelledby="about-tab">

        <div class="grid grid-cols-3 gap-4">
            <div class="md:w-3/4 col-span-2">
                <h2 class="mb-3 text-3xl font-extrabold tracking-tight text-gray-900 dark:text-white"><%= @category.name %></h2>
                <p class="mb-3 text-gray-500 dark:text-gray-400"><%= @category.description %></p>
                <a href="#" class="inline-flex items-center font-medium text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-blue-700">
                <%= link_to new_category_path, class: "inline-flex items-center font-medium text-green-700 hover:text-green-700 dark:text-green-500 hover:text-white" do %>
                    Create Category
                    <svg class="w-2.5 h-2.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                    <%end %>
                </a>

                <a href="#" class="inline-flex items-center font-medium text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-blue-700">
                <%= link_to edit_category_path(@category), class: "inline-flex items-center font-medium text-blue-600 hover:text-blue-600 dark:text-blue-800 hover:text-white" do %>
                    Edit Category

                    <svg class="w-2.5 h-2.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                        <% end %>
                </a>



                 <a href="#" class="inline-flex items-center font-medium text-blue-600 hover:text-blue-800 dark:text-blue-500 dark:hover:text-blue-700">
                 <%= button_to category_path(@category), method: :delete, class: "inline-flex items-center font-medium text-red-600 hover:text-red-800 dark:text-red-500 hover:text-white" do %>
                    Delete Category
                    <svg class="w-2.5 h-2.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                        <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
                    </svg>
                        <% end %>
                </a>
            </div>

            <div class="md:w-1/4 md:text-right mt-4 md:mt-0 justify-items-end">
                <span class="text-9xl"><%= @category.icon %></span>
            </div>
        </div>

    </div>
</div>


        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-800" id="events" role="tabpanel" aria-labelledby="events-tab">
            <h2 class="mb-5 text-2xl font-extrabold tracking-tight text-gray-900 dark:text-white">Event information on this category</h2>
            <!-- List -->
            <ul role="list" class="space-y-4 text-gray-500 dark:text-gray-400">
                <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-blue-600 dark:text-blue-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                    </svg>
                    <span class="leading-tight">Number of Events:: <%= @event_count %></span>
                </li>

                  <li class="flex space-x-2 rtl:space-x-reverse items-center">
                    <svg class="flex-shrink-0 w-3.5 h-3.5 text-orange-600 dark:text-orange-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5Zm3.707 8.207-4 4a1 1 0 0 1-1.414 0l-2-2a1 1 0 0 1 1.414-1.414L9 10.586l3.293-3.293a1 1 0 0 1 1.414 1.414Z"/>
                    </svg>
                    <span class="leading-tight">Other information</span>
                </li>
            </ul>
        </div>
        <div class="hidden p-4 bg-white rounded-lg md:p-8 dark:bg-gray-800" id="popularity" role="tabpanel" aria-labelledby="popularity-tab">
            <dl class="grid max-w-screen-xl grid-cols-2 gap-8 p-4 mx-auto text-gray-900 sm:grid-cols-3 xl:grid-cols-6 dark:text-white sm:p-8">
                <div class="flex flex-col">
                    <dt class="mb-2 text-3xl font-extrabold">73M+</dt>
                    <dd class="text-gray-500 dark:text-gray-400">Co-oporate</dd>
                </div>
                <div class="flex flex-col">
                    <dt class="mb-2 text-3xl font-extrabold">100M+</dt>
                    <dd class="text-gray-500 dark:text-gray-400">Private Events</dd>
                </div>
                <div class="flex flex-col">
                    <dt class="mb-2 text-3xl font-extrabold">1000s</dt>
                    <dd class="text-gray-500 dark:text-gray-400">Public Events</dd>
                </div>

                <div class="flex flex-col">
                    <dt class="mb-2 text-3xl font-extrabold">1000s</dt>
                    <dd class="text-gray-500 dark:text-gray-400">Others</dd>
                </div>
            </dl>
        </div>
    </div>
</div>


<% end %>
<%= render "shared/dashboard" %>